<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_pago_efectivo</name>
   <tag></tag>
   <elementGuidId>a234b87f-3e2c-445e-88cc-4a20b54b8e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sell-order-option-resources.SellOrder.payment_types.recaudo_en_efectivo&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
