<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_rdenesrdenes</name>
   <tag></tag>
   <elementGuidId>a3ea779a-7a5f-4560-9f31-78afce64e1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiList-root-431.jss435 > a.MuiButtonBase-root-234.MuiListItem-root-339.MuiMenuItem-root-336.jss333.jss326.MuiMenuItem-gutters-337.MuiListItem-gutters-344.MuiListItem-button-345</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/main/div/div/div[2]/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-234 MuiListItem-root-339 MuiMenuItem-root-336 jss333 jss326 MuiMenuItem-gutters-337 MuiListItem-gutters-344 MuiListItem-button-345</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/SellOrder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ÓrdenesÓrdenes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss2 jss1&quot;]/div[1]/div[@class=&quot;layout jss161&quot;]/div[@class=&quot;jss162&quot;]/main[@class=&quot;jss163&quot;]/div[@class=&quot;MuiDrawer-root-311 jss307 jss310 MuiDrawer-docked-312&quot;]/div[@class=&quot;MuiPaper-root-183 MuiDrawer-paper-313 MuiDrawer-paperAnchorLeft-314 jss308 jss309 MuiDrawer-paperAnchorDockedLeft-318 MuiPaper-elevation16-202&quot;]/div[@class=&quot;MuiBox-root-244 jss331&quot;]/div[@class=&quot;MuiBox-root-244 jss332 jss323 jss324&quot;]/div[@class=&quot;MuiCollapse-container-437 MuiCollapse-entered-438&quot;]/div[@class=&quot;MuiCollapse-wrapper-440&quot;]/div[@class=&quot;MuiCollapse-wrapperInner-441&quot;]/div[@class=&quot;MuiList-root-431 jss435&quot;]/a[@class=&quot;MuiButtonBase-root-234 MuiListItem-root-339 MuiMenuItem-root-336 jss333 jss326 MuiMenuItem-gutters-337 MuiListItem-gutters-344 MuiListItem-button-345&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div/div/div[2]/div/div/div/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventas'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envío de mercancía'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Órdenes']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/SellOrder')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/SellOrder' and (text() = 'ÓrdenesÓrdenes' or . = 'ÓrdenesÓrdenes')]</value>
   </webElementXpaths>
</WebElementEntity>
