<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_siguiente</name>
   <tag></tag>
   <elementGuidId>853a6648-42fa-4ec4-9577-d387831dc4cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.MuiButtonBase-root-234.MuiButton-root-1383.MuiButton-contained-1391.jss1368.MuiButton-containedPrimary-1392.MuiButton-containedSizeSmall-1400.MuiButton-sizeSmall-1402 > span.MuiButton-label-1384</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(.,'Siguiente')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-label-1384</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Siguiente</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root jss2 jss1&quot;]/div[1]/div[@class=&quot;layout jss161&quot;]/div[@class=&quot;jss162&quot;]/main[@class=&quot;jss163&quot;]/div[@class=&quot;jss164 jss160&quot;]/div[@class=&quot;MuiBox-root-244 jss1117&quot;]/header[@class=&quot;MuiPaper-root-183 MuiAppBar-root-172 MuiAppBar-positionFixed-173 MuiAppBar-colorPrimary-179 jss1365 mui-fixed MuiPaper-elevation4-190&quot;]/div[@class=&quot;MuiToolbar-root-211 MuiToolbar-dense-214 jss1366&quot;]/div[@class=&quot;MuiBox-root-244 jss1367&quot;]/div[@class=&quot;MuiGrid-root-1154 MuiGrid-container-1155 MuiGrid-wrap-xs-nowrap-1161 MuiGrid-justify-xs-space-between-1174&quot;]/div[@class=&quot;MuiGrid-root-1154 MuiGrid-item-1156&quot;]/div[@class=&quot;MuiGrid-root-1154 MuiGrid-container-1155 MuiGrid-spacing-xs-1-1177 MuiGrid-wrap-xs-nowrap-1161&quot;]/div[@class=&quot;MuiGrid-root-1154 MuiGrid-item-1156&quot;]/button[@class=&quot;MuiButtonBase-root-234 MuiButton-root-1383 MuiButton-contained-1391 jss1368 MuiButton-containedPrimary-1392 MuiButton-containedSizeSmall-1400 MuiButton-sizeSmall-1402&quot;]/span[@class=&quot;MuiButton-label-1384&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div[2]/div/header/div/div/div/div[2]/div/div[3]/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver atrás'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver resumen'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/preceding::span[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Siguiente']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Siguiente' or . = 'Siguiente')]</value>
   </webElementXpaths>
</WebElementEntity>
